  CREATE TABLE "AGENT_CUSTOMERS"
   (	"ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE NOKEEP NOSCALE NOT NULL ENABLE ANNOTATIONS (Display 'Customer ID', Description 'Unique identifier for a customer.'),
	"FIRST_NAME" VARCHAR2(255 CHAR) NOT NULL ENABLE ANNOTATIONS (Display 'First name', Description 'Customer given name.'),
	"LAST_NAME" VARCHAR2(255 CHAR) NOT NULL ENABLE ANNOTATIONS (Display 'Last name', Description 'Customer family name.'),
	"EMAIL" VARCHAR2(255 CHAR) NOT NULL ENABLE ANNOTATIONS (Display 'Email address', Description 'Unique customer email address.', Sensitive),
	"CITY" VARCHAR2(255 CHAR) ANNOTATIONS (Display 'City', Description 'Customer city of residence.'),
	"COUNTRY" VARCHAR2(50 CHAR) ANNOTATIONS (Display 'Country', Description 'Customer country of residence.'),
	"GENDER" VARCHAR2(30 CHAR) ANNOTATIONS (Display 'Gender', Description 'Customer gender.', Sensitive),
	"DATE_OF_BIRTH" DATE ANNOTATIONS (Display 'Date of birth', Description 'Customer date of birth.', Sensitive),
	"PHONE" VARCHAR2(30 CHAR) ANNOTATIONS (Display 'Phone number', Description 'Customer phone number.', Sensitive),
	"POSTAL_CODE" VARCHAR2(30 CHAR) ANNOTATIONS (Display 'Postal code', Description 'Customer postal code.', Sensitive),
	"CREATED_AT" TIMESTAMP (6) DEFAULT systimestamp NOT NULL ENABLE ANNOTATIONS (Display 'Created at', Description 'Timestamp when the customer record was created.'),
	 CONSTRAINT "AGENT_CUSTOMERS_GENDER_CK" CHECK (gender in ('Male', 'Female')) ENABLE,
	 CONSTRAINT "AGENT_CUSTOMERS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE,
	 CONSTRAINT "AGENT_CUSTOMERS_EMAIL_UK" UNIQUE ("EMAIL")
  USING INDEX  ENABLE
   ) ANNOTATIONS (Display 'Customers', Description 'Customers who purchase products.');

  CREATE TABLE "AGENT_PRODUCTS"
   (	"ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE NOKEEP NOSCALE NOT NULL ENABLE ANNOTATIONS (Display 'Product ID', Description 'Unique identifier for a product.'),
	"NAME" VARCHAR2(50 CHAR) NOT NULL ENABLE ANNOTATIONS (Display 'Product name', Description 'Name of the product.'),
	"DESCRIPTION" VARCHAR2(500 CHAR) ANNOTATIONS (Display 'Product description', Description 'Description of the product.'),
	"SKU" VARCHAR2(30 CHAR) NOT NULL ENABLE ANNOTATIONS (Display 'SKU', Description 'Unique stock-keeping unit for the product.'),
	"UNIT" NUMBER(12,2) DEFAULT 0 NOT NULL ENABLE ANNOTATIONS (Display 'Units in stock', Description 'Current quantity of the product in stock.'),
	"UNIT_PRICE" NUMBER(12,2) NOT NULL ENABLE ANNOTATIONS (Display 'Unit price', Description 'Standard selling price for one unit of the product.'),
	"CREATED_AT" TIMESTAMP (6) DEFAULT systimestamp NOT NULL ENABLE ANNOTATIONS (Display 'Created at', Description 'Timestamp when the product record was created.'),
	 CONSTRAINT "AGENT_PRODUCTS_UNIT_CK" CHECK (unit >= 0) ENABLE,
	 CONSTRAINT "AGENT_PRODUCTS_PRICE_CK" CHECK (unit_price >= 0) ENABLE,
	 CONSTRAINT "AGENT_PRODUCTS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE,
	 CONSTRAINT "AGENT_PRODUCTS_SKU_UK" UNIQUE ("SKU")
  USING INDEX  ENABLE
   ) ANNOTATIONS (Display 'Products', Description 'Products available for sale.');

  CREATE TABLE "AGENT_PROMOTIONS"
   (	"ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE NOKEEP NOSCALE NOT NULL ENABLE ANNOTATIONS (Display 'Promotion ID', Description 'Unique identifier for a promotion.'),
	"NAME" VARCHAR2(255 CHAR) NOT NULL ENABLE ANNOTATIONS (Display 'Promotion name', Description 'Name of the promotion.'),
	"CODE" VARCHAR2(10 CHAR) NOT NULL ENABLE ANNOTATIONS (Display 'Promotion code', Description 'Unique code used to identify the promotion.'),
	"DATE_BEGIN" DATE NOT NULL ENABLE ANNOTATIONS (Display 'Start date', Description 'First date on which the promotion is valid.'),
	"DATE_END" DATE ANNOTATIONS (Display 'End date', Description 'Last date on which the promotion is valid.'),
	"DISCOUNT_PERCENTAGE" NUMBER(5,2) NOT NULL ENABLE ANNOTATIONS (Display 'Discount percentage', Description 'Percentage discount applied by the promotion.'),
	"CREATED_AT" TIMESTAMP (6) DEFAULT systimestamp NOT NULL ENABLE ANNOTATIONS (Display 'Created at', Description 'Timestamp when the promotion record was created.'),
	 CONSTRAINT "AGENT_PROMOTIONS_DATES_CK" CHECK (date_end >= date_begin) ENABLE,
	 CONSTRAINT "AGENT_PROMOTIONS_DISCOUNT_CK" CHECK (discount_percentage between 0 and 100) ENABLE,
	 CONSTRAINT "AGENT_PROMOTIONS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE,
	 CONSTRAINT "AGENT_PROMOTIONS_CODE_UK" UNIQUE ("CODE")
  USING INDEX  ENABLE
   ) ANNOTATIONS (Display 'Promotions', Description 'Promotional discounts that can be applied to sales.');

  CREATE TABLE "AGENT_SALES"
   (	"ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE NOKEEP NOSCALE NOT NULL ENABLE ANNOTATIONS (Display 'Sale ID', Description 'Unique identifier for a sale.'),
	"PRODUCT_ID" NUMBER NOT NULL ENABLE ANNOTATIONS (Display 'Product ID', Description 'Product sold in this sale.'),
	"CUSTOMER_ID" NUMBER NOT NULL ENABLE ANNOTATIONS (Display 'Customer ID', Description 'Customer who made the purchase.'),
	"PROMOTION_ID" NUMBER ANNOTATIONS (Display 'Promotion ID', Description 'Promotion applied to the sale, if any.'),
	"CHANNEL_ID" NUMBER ANNOTATIONS (Display 'Sales channel ID', Description 'Identifier of the channel through which the sale was made.'),
	"DATE_OF_SALE" DATE DEFAULT trunc(sysdate) NOT NULL ENABLE ANNOTATIONS (Display 'Sale date', Description 'Date on which the sale occurred.'),
	"QUANTITY" NUMBER(12,2) NOT NULL ENABLE ANNOTATIONS (Display 'Quantity', Description 'Number of product units sold.'),
	"UNIT_PRICE" NUMBER(12,2) NOT NULL ENABLE ANNOTATIONS (Display 'Unit price', Description 'Price charged for one product unit in this sale.'),
	"CREATED_AT" TIMESTAMP (6) DEFAULT systimestamp NOT NULL ENABLE ANNOTATIONS (Display 'Created at', Description 'Timestamp when the sale record was created.'),
	 CONSTRAINT "AGENT_SALES_QUANTITY_CK" CHECK (quantity > 0) ENABLE,
	 CONSTRAINT "AGENT_SALES_UNIT_PRICE_CK" CHECK (unit_price >= 0) ENABLE,
	 CONSTRAINT "AGENT_SALES_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ANNOTATIONS (Display 'Sales', Description 'Individual product sales to customers, optionally with a promotion.');

  ALTER TABLE "AGENT_SALES" ADD CONSTRAINT "AGENT_SALES_CUSTOMER_FK" FOREIGN KEY ("CUSTOMER_ID")
	  REFERENCES "AGENT_CUSTOMERS" ("ID") ENABLE;
  ALTER TABLE "AGENT_SALES" ADD CONSTRAINT "AGENT_SALES_PRODUCT_FK" FOREIGN KEY ("PRODUCT_ID")
	  REFERENCES "AGENT_PRODUCTS" ("ID") ENABLE;
  ALTER TABLE "AGENT_SALES" ADD CONSTRAINT "AGENT_SALES_PROMOTION_FK" FOREIGN KEY ("PROMOTION_ID")
	  REFERENCES "AGENT_PROMOTIONS" ("ID") ON DELETE SET NULL ENABLE;

  CREATE INDEX "AGENT_SALES_CUSTOMER_IDX" ON "AGENT_SALES" ("CUSTOMER_ID")
  ;

  CREATE INDEX "AGENT_SALES_DATE_IDX" ON "AGENT_SALES" ("DATE_OF_SALE")
  ;

  CREATE INDEX "AGENT_SALES_PROMOTION_IDX" ON "AGENT_SALES" ("PROMOTION_ID")
  ;

  CREATE INDEX "AGENT_SALES_PRODUCT_IDX" ON "AGENT_SALES" ("PRODUCT_ID")
  ;
