create table "AGENT_CUSTOMERS" (
   "ID"            number generated by default on null as identity minvalue 1 maxvalue 9999999999999999999999999999 increment
   by 1 start with 1 cache 20 noorder nocycle nokeep noscale not null enable annotations ( display 'Customer ID',description 'Unique identifier for a customer.'
   ),
   "FIRST_NAME"    varchar2(255 char) not null enable annotations ( display 'First name',description 'Customer given name.' )
   ,
   "LAST_NAME"     varchar2(255 char) not null enable annotations ( display 'Last name',description 'Customer family name.' )
   ,
   "EMAIL"         varchar2(255 char) not null enable annotations ( display 'Email address',description 'Unique customer email address.'
   ,sensitive ),
   "CITY"          varchar2(255 char)
      annotations ( display 'City',description 'Customer city of residence.' ),
   "COUNTRY"       varchar2(50 char)
      annotations ( display 'Country',description 'Customer country of residence.' ),
   "GENDER"        varchar2(30 char)
      annotations ( display 'Gender',description 'Customer gender.',sensitive ),
   "DATE_OF_BIRTH" date
      annotations ( display 'Date of birth',description 'Customer date of birth.',sensitive ),
   "PHONE"         varchar2(30 char)
      annotations ( display 'Phone number',description 'Customer phone number.',sensitive ),
   "POSTAL_CODE"   varchar2(30 char)
      annotations ( display 'Postal code',description 'Customer postal code.',sensitive ),
   "CREATED_AT"    timestamp(6) default systimestamp not null enable annotations ( display 'Created at',description 'Timestamp when the customer record was created.'
   ),
   constraint "AGENT_CUSTOMERS_GENDER_CK"
      check ( gender in ( 'Male',
                          'Female' ) ) enable,
   constraint "AGENT_CUSTOMERS_PK" primary key ( "ID" )
      using index enable,
   constraint "AGENT_CUSTOMERS_EMAIL_UK" unique ( "EMAIL" )
      using index enable
) annotations ( display 'Customers',description 'Customers who purchase products.' );

create table "AGENT_PRODUCTS" (
   "ID"          number generated by default on null as identity minvalue 1 maxvalue 9999999999999999999999999999 increment by
   1 start with 1 cache 20 noorder nocycle nokeep noscale not null enable annotations ( display 'Product ID',description 'Unique identifier for a product.'
   ),
   "NAME"        varchar2(50 char) not null enable annotations ( display 'Product name',description 'Name of the product.' ),
   "DESCRIPTION" varchar2(500 char)
      annotations ( display 'Product description',description 'Description of the product.' ),
   "SKU"         varchar2(30 char) not null enable annotations ( display 'SKU',description 'Unique stock-keeping unit for the product.'
   ),
   "UNIT"        number(12,2) default 0 not null enable annotations ( display 'Units in stock',description 'Current quantity of the product in stock.'
   ),
   "UNIT_PRICE"  number(12,2) not null enable annotations ( display 'Unit price',description 'Standard selling price for one unit of the product.'
   ),
   "CREATED_AT"  timestamp(6) default systimestamp not null enable annotations ( display 'Created at',description 'Timestamp when the product record was created.'
   ),
   constraint "AGENT_PRODUCTS_UNIT_CK" check ( unit >= 0 ) enable,
   constraint "AGENT_PRODUCTS_PRICE_CK" check ( unit_price >= 0 ) enable,
   constraint "AGENT_PRODUCTS_PK" primary key ( "ID" )
      using index enable,
   constraint "AGENT_PRODUCTS_SKU_UK" unique ( "SKU" )
      using index enable
) annotations ( display 'Products',description 'Products available for sale.' );

create table "AGENT_PROMOTIONS" (
   "ID"                  number generated by default on null as identity minvalue 1 maxvalue 9999999999999999999999999999 increment
   by 1 start with 1 cache 20 noorder nocycle nokeep noscale not null enable annotations ( display 'Promotion ID',description
   'Unique identifier for a promotion.' ),
   "NAME"                varchar2(255 char) not null enable annotations ( display 'Promotion name',description 'Name of the promotion.'
   ),
   "CODE"                varchar2(10 char) not null enable annotations ( display 'Promotion code',description 'Unique code used to identify the promotion.'
   ),
   "DATE_BEGIN"          date not null enable annotations ( display 'Start date',description 'First date on which the promotion is valid.'
   ),
   "DATE_END"            date
      annotations ( display 'End date',description 'Last date on which the promotion is valid.' ),
   "DISCOUNT_PERCENTAGE" number(5,2) not null enable annotations ( display 'Discount percentage',description 'Percentage discount applied by the promotion.'
   ),
   "CREATED_AT"          timestamp(6) default systimestamp not null enable annotations ( display 'Created at',description 'Timestamp when the promotion record was created.'
   ),
   constraint "AGENT_PROMOTIONS_DATES_CK" check ( date_end >= date_begin ) enable,
   constraint "AGENT_PROMOTIONS_DISCOUNT_CK" check ( discount_percentage between 0 and 100 ) enable,
   constraint "AGENT_PROMOTIONS_PK" primary key ( "ID" )
      using index enable,
   constraint "AGENT_PROMOTIONS_CODE_UK" unique ( "CODE" )
      using index enable
) annotations ( display 'Promotions',description 'Promotional discounts that can be applied to sales.' );

create table "AGENT_SALES" (
   "ID"           number generated by default on null as identity minvalue 1 maxvalue 9999999999999999999999999999 increment by
   1 start with 1 cache 20 noorder nocycle nokeep noscale not null enable annotations ( display 'Sale ID',description 'Unique identifier for a sale.'
   ),
   "PRODUCT_ID"   number not null enable annotations ( display 'Product ID',description 'Product sold in this sale.' ),
   "CUSTOMER_ID"  number not null enable annotations ( display 'Customer ID',description 'Customer who made the purchase.' ),
   "PROMOTION_ID" number
      annotations ( display 'Promotion ID',description 'Promotion applied to the sale, if any.' ),
   "CHANNEL_ID"   number
      annotations ( display 'Sales channel ID',description 'Identifier of the channel through which the sale was made.' ),
   "DATE_OF_SALE" date default trunc(sysdate) not null enable annotations ( display 'Sale date',description 'Date on which the sale occurred.'
   ),
   "QUANTITY"     number(12,2) not null enable annotations ( display 'Quantity',description 'Number of product units sold.' )
   ,
   "UNIT_PRICE"   number(12,2) not null enable annotations ( display 'Unit price',description 'Price charged for one product unit in this sale.'
   ),
   "CREATED_AT"   timestamp(6) default systimestamp not null enable annotations ( display 'Created at',description 'Timestamp when the sale record was created.'
   ),
   constraint "AGENT_SALES_QUANTITY_CK" check ( quantity > 0 ) enable,
   constraint "AGENT_SALES_UNIT_PRICE_CK" check ( unit_price >= 0 ) enable,
   constraint "AGENT_SALES_PK" primary key ( "ID" )
      using index enable
) annotations ( display 'Sales',description 'Individual product sales to customers, optionally with a promotion.' );

alter table "AGENT_SALES"
   add constraint "AGENT_SALES_CUSTOMER_FK"
      foreign key ( "CUSTOMER_ID" )
         references "AGENT_CUSTOMERS" ( "ID" )
      enable;
alter table "AGENT_SALES"
   add constraint "AGENT_SALES_PRODUCT_FK"
      foreign key ( "PRODUCT_ID" )
         references "AGENT_PRODUCTS" ( "ID" )
      enable;
alter table "AGENT_SALES"
   add constraint "AGENT_SALES_PROMOTION_FK"
      foreign key ( "PROMOTION_ID" )
         references "AGENT_PROMOTIONS" ( "ID" )
            on delete set null
      enable;

create index "AGENT_SALES_CUSTOMER_IDX" on
   "AGENT_SALES" (
      "CUSTOMER_ID"
   );

create index "AGENT_SALES_DATE_IDX" on
   "AGENT_SALES" (
      "DATE_OF_SALE"
   );

create index "AGENT_SALES_PROMOTION_IDX" on
   "AGENT_SALES" (
      "PROMOTION_ID"
   );

create index "AGENT_SALES_PRODUCT_IDX" on
   "AGENT_SALES" (
      "PRODUCT_ID"
   );